theme: jekyll-theme-cayman
title: Active Localization of Multiple Targets Using Noisy Relative Measurements
description: Project page for our paper on active target localization (WAFR 2020)
github:
  is_project_page: false
