theme: jekyll-theme-cayman
title: Active Localization of Multiple Targets Using Noisy Relative Measurements (WAFR 2020)
description: [Selim Engin](https://ksengin.github.io/) and [Volkan Isler](https://www-users.cs.umn.edu/~isler/)
github:
  is_project_page: false
