theme: jekyll-theme-cayman
title: Active Localization of Multiple Targets from Noisy Relative Measurements
description: Project page for the Active Target Localization paper (WAFR 2020)
github:
  is_project_page: false
